name: sync to gitee

on:
  push:
    branches:
      - develop
    
jobs:
  mirror:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token
        with:
          src: github/nocturnal-chorus
          dst: gitee/nocturnal-chorus
          force_update: true
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          src_account_type: org
          dst_account_type: org
          static_list: chorus-media-player
